"""Embed the mpv assets into the C++ build.

The Lua beacon is extracted verbatim from the Python source. The input.conf is not a
constant there - it is three lines written inline in MpvDriver - so it is reproduced
here with the reason it exists:

    SPACE          cycle pause
    MBTN_LEFT      -> the Lua's syncplayer-click: arm a 450 ms deferred pause
    MBTN_LEFT_DBL  -> the Lua's syncplayer-dbl: cancel it and cycle fullscreen

input.conf is the TOP of mpv's binding chain, so it wins over mpv's defaults and over
Lua key bindings, which is what makes the double-click handling deterministic.

Writes cpp/src/core/mpv_assets.cpp with both sources as raw string literals.
"""
import io
import os

REPO = r"C:\Users\Zcc09\SyncPlayer"
CPP = os.path.join(REPO, "cpp")

lua_path = os.path.join(CPP, "assets", "syncplayer_events.lua")
lua = io.open(lua_path, encoding="utf-8").read()

input_conf = (
    "# Generated by SyncPlayer. The Lua beacon implements syncplayer-click and\n"
    "# syncplayer-dbl; input.conf is the top of mpv's binding chain, so these win over\n"
    "# mpv's defaults and over Lua key bindings - which is what makes the deferred\n"
    "# click-to-pause and the double-click fullscreen deterministic at any DPI.\n"
    "SPACE cycle pause\n"
    "MBTN_LEFT script-binding syncplayer-click\n"
    "MBTN_LEFT_DBL script-binding syncplayer-dbl\n"
)
io.open(os.path.join(CPP, "assets", "input.conf"), "w", encoding="utf-8",
        newline="\n").write(input_conf)


def literal(name, text):
    delim = name
    while ('(' + delim + ')') in text:
        delim += "X"
    return 'extern const char* const %s = R"%s(%s)%s";\n' % (
        name, delim, text.rstrip("\n"), delim)


out = ["// Generated by cpp/tools/embed_assets.py - do not edit by hand.",
       "//",
       "// Both sources come from the Python implementation, so the C++ port drives mpv",
       "// with the same beacon and the same key bindings.",
       "",
       "namespace sp {",
       "",
       literal("kLuaBeaconSource", lua),
       "",
       literal("kInputConfSource", input_conf),
       "",
       "}  // namespace sp",
       ""]
dest = os.path.join(CPP, "src", "core", "mpv_assets.cpp")
io.open(dest, "w", encoding="utf-8", newline="\n").write("\n".join(out))
print("wrote %s (%d bytes)" % (dest, os.path.getsize(dest)))
print("  lua: %d lines | input.conf: %d lines"
      % (lua.count("\n"), input_conf.count("\n")))
assert "SPACE cycle pause" in input_conf
assert "script-binding syncplayer-click" in input_conf
